version: 2.1

setup-env: &setup-env
  run:
    name: Setting up env variables
    command: |
      eval echo "export SLACK_CHANNELID" >> $BASH_ENV
      eval echo "export SLACK_USERID1" >> $BASH_ENV
      eval echo "export SLACK_USERID2" >> $BASH_ENV
      eval echo "export SLACK_WEBHOOK" >> $BASH_ENV

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:11.7.0

orbs:
  win: circleci/windows@1.0.0
  slack: circleci/slack@3.4.0

jobs:
  build-docker:
    <<: *defaults
    steps:
      - checkout
      - slack/notify:
          channel: $SLACK_CHANNELID
          color: "#0a8c37"
          mentions: $SLACK_USERID1
          message: Aware Ricky started building on CircleCI
      - restore_cache:
          keys:
            - cache-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - cache-
      - run:
          name: Installing gulp-cli
          command: sudo npm install -g gulp-cli
      - run:
          name: Installing dependencies
          command: npm install
      - save_cache:
          paths:
            - ./node_modules/
          key: cache-{{ checksum "package.json" }}
      - run:
          name: Build
          command: gulp build
  build-windows:
    executor: win/vs2019
    steps:
      - checkout
      - run:
          name: Installing gulp-cli
          command: npm install -g gulp-cli
      - run:
          name: Installing dependencies
          command: npm install

workflows:
  build:
    jobs:
      - build-docker
      - build-windows
