version: 2.1

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:11.7.0

orbs:
  win: circleci/windows@1.0.0

jobs:
  build-docker:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - cache-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - cache-
      - run:
          name: Installing gulp-cli
          command: sudo npm install -g gulp-cli
      - run:
          name: Installing Dependencies
          command: npm install
      - save_cache:
          paths:
            - ./node_modules/
          key: cache-{{ checksum "package.json" }}
      - run:
          name: Run game
          command: gulp
      - run:
          name: End job
          command: circleci-agent step halt
  build-windows:
    executor: win/vs2019
    steps:
      - checkout
      - run:
          command: echo 'This is powershell'
          shell: powershell.exe
      - run:
          name: Install Dependencies
          command: npm install

workflows:
  build:
    jobs:
      - build-docker
      - build-windows
